### ISSUE TITLE
Thredds S3 Caching should use entry creation time instead of last access time for expiry

### ISSUE THREAD

**Issue by jonescc** [aodn/thredds#10]
Thredds S3 caching is currently set to expire cache entries using the last access time of the entry.  This can result in updates to s3 not being reflected in thredds within a predictable time frame.  Would be better to expire cache entries based on creation time to ensure entries don't become stale.

**Comment by julian1** [comment]
So if someone regularly touches/accesses the file - then it will never see the update?

**Comment by julian1** [comment]
https://github.com/aodn/thredds/pull/11

**Comment by jonescc** [comment]
Yes, currently if a file is being regularly accessed - it won't be evicted from the cache and will become stale.
