### ISSUE TITLE
thredds fails to serve file over opendap

### ISSUE THREAD

**Issue by julian1** [aodn/thredds#13]
select http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/L3S-1d/day/2017/catalog.html?dataset=IMOS/SRS/SST/ghrsst/L3S-1d/day/2017/20170115032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc

Then choose opendap and select binary for the following url,

http://thredds.aodn.org.au/thredds/dodsC/IMOS/SRS/SST/ghrsst/L3S-1d/day/2017/20170115032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1d_day.nc.dods?

I get the following error,
```
Error {
    code = 403;
    message = "Request too big=540.63006 Mbytes, max=500.0";
};
```

**Comment by jonescc** [comment]
The limit is configured in threddsConfig:  http://www.unidata.ucar.edu/software/thredds/current/tds/reference/ThreddsConfigXMLFile.html#opendap

**Comment by jonescc** [comment]
Thredds actually sends only one variable at a time reading each variable fully into memory before sending it so opendap requests like this would actually be limited by the in memory size of the largest variable its sending.

**Comment by pblain** [comment]
Closing
